### ISSUE TITLE
Data Error loading d878.csv in CPS software

### ISSUE THREAD

**Issue by mckoss** [QCaudron/repeater_roundabout#11]
I just tested the latest files from RR from the downloaded zip file.  I get a Data Error message when loading the d878.csv file.

Investigating now...

![image](https://user-images.githubusercontent.com/82750/200197106-2770b4e8-8e30-4e19-bf83-5219394af733.png)

**Comment by mckoss** [comment]
Looks like the zipped csv file has only linefeed terminators and the CPS software doesn't recognize the line endings (it's a Windows-only software).

**Comment by mckoss** [comment]
Fixed by #12

**Comment by QCaudron** [comment]
Thanks !
