### ISSUE TITLE
Add Parrot channel side by side with Repeater channels?

### ISSUE THREAD

**Issue by mckoss** [QCaudron/repeater_roundabout#15]
I sometimes find it useful to test my repeater connection before calling using the Parrot channel.  It's pretty standard across DMR repeaters to support it - so I think I can just add it in whenever there is a DMR repeater as well.

**Comment by QCaudron** [comment]
Addressed by #23

**Comment by mckoss** [comment]
Not completely - #23 adds the talk groups - but I need a PR to add additional channels...

**Comment by mckoss** [comment]
It works.  You can select a repeater, and then use the menus to switch to Parrot.  I was able to use this to test my connections to the repeater.
