### ISSUE TITLE
All CSV's in D878 zip file need to be CR/LF line terminated

### ISSUE THREAD

**Issue by mckoss** [QCaudron/repeater_roundabout#18]
Since we don't (currently) generate these files - they are stored in the local filesystem line termination mode.  On linux/Mac this is LF only.

We should either:

- Generate these files from the channel data (preferred).
- Pre-process the files before adding to the zip file.

**Comment by QCaudron** [comment]
You can instruct git not to change things, which has been a problem on my side :

```bash
git config core.autocrlf false
```

If certain radio files require `\n` or `\r\n` line endings, we can ensure that is preserved in CI; I can put a quick thing together. Can you confirm which files need which ? I know your D878.csv file write uses `\r\n` as a line terminator; we just need to ensure git isn't undoing this.

**Comment by QCaudron** [comment]
Hmm. I'm struggling with this one. I can write a file with `\r\n` and when I read it back, I only see `\n` ( currently Windows; can pull out the Mac later ).

**Comment by mckoss** [comment]
I wouldn't mess with the git config - I think I prefer files on the repo to be LF-terminated.

[RFC 4180](https://www.loc.gov/preservation/digital/formats/fdd/fdd000323.shtml) Actually specifies CR-LF line endings.

But I think the answer is just to address #6 .

**Comment by QCaudron** [comment]
This one is driving me a little nuts. On my system, I see CRLF. The version in git is not showing CRLF ( and the new CI is failing ).

**Comment by mckoss** [comment]
#23 Fixes
