### ISSUE TITLE
Add Internet info for repeaters?

### ISSUE THREAD

**Issue by mckoss** [QCaudron/repeater_roundabout#20]
Do we have time to add Allstar and Echolink information to our repeater list?  We do have a big following outside the area, so it might be nice to document the ID's needed to connect to the repeaters in our list that support it.

Maybe we can get AB6MB or another frequent internet user to pitch in with the research?

**Comment by QCaudron** [comment]
It's a lot of work and, while it would be great, I don't necessarily want
to spend time sleuthing Geocities-like websites for info that, in my
experience, is often outdated ! I know Jeff was working on this but I heard
he lost his progress and I'm not sure how far he has come. Very happy to
check in with him.

If we want to do this, I think it would go on a separate page, adding a
field to the .json and generating a new table. If you want to go down this
route, perhaps let's coordinate with Jeff ?


Quentin CAUDRON, PhD
quentincaudron.com

**Comment by QCaudron** [comment]
Jeff said he'd let me know of his progress today or tomorrow.

**Comment by mckoss** [comment]
https://docs.google.com/spreadsheets/d/15P5zgdEZhchNI1Vu2DLTpo1CVxMiYSrBG7GhCbF3lbw/edit#gid=0

Snapshot:

  |   |   |   |   |   |   | ECHOLINK
-- | -- | -- | -- | -- | -- | -- | --
RASC | Lyman Hill | FM | 145.19 | -0.6 | 127.3 | N7GDE | KI7ZI-R
Eatonville | Eatonville | FM | 442.725 | 5 | 103.5 | W7EAT | W7EAT-R
West Seattle | West Seattle | FM | 145.13 | -0.6 | 103.5 | W7AW | W7AW-R
Eatonville | Eatonville | FM | 146.7 | -0.6 | 103.5 | W7EAT | W7EAT-R
Lake Wash. | Kirkland | FM | 145.49 | -0.6 | 103.5 | K7LWH | K7LWH-R
PSRG | Seattle | FM | x | x | x | WW7PSR | WW7PSR-R
  |   |   |   |   |   |   |  
  |   |   |   |   |   |   | ALLSTAR
PSRG | Seattle | FM | 146.96 | -0.6 | 103.5 | WW7PSR | 2462
PSRG | Seattle | FM | 52.87 | -1.7 | 103.5 | WW7PSR | 2464
Seattle ACS | Seattle | FM | 442.3 | 5 | 141.3 | W7ACS | 48832
Seattle ACS | Seattle | FM | 443.475 | 5 | 141.3 | W7ACS | 48836
Seattle ACS | Seattle | FM | 442.875 | 5 | 141.3 | W7ACS | 48842
Seattle ACS | Seattle | FM | 444.55 | 5 | 141.3 | W7ACS | 48844
West Seattle | West Seattle | FM | 441.8 | 5 | 141.3 | W7AW | 56575
Eatonville | Eatonville | FM | 146.7 | -0.6 | 103.5 | W7EAT | 41291
WW7SEA | Seattle | FM | 444.7 | 5 | 103.5 | WW7SEA | 48845
Lake Wash. | Kirkland | FM | 145.49 | -0.6 | 103.5 | K7LWH | 51860
Seattle ACS | Lake Forest Park | FM | 440.6 | 5 | 141.3 | W7ACS | 48834
Seattle ACS | White Center | FM | 443.2 | 5 | 141.3 | W7ACS | 48838
```
