### ISSUE TITLE
Spectrum display

### ISSUE THREAD

**Issue by mckoss** [QCaudron/repeater_roundabout#26]
I would love to see how the repeaters fit into the full Band plan.  I think it could be a cool and fun display for the site.

For now - this will just be an experiment.  I plan to incorporate the full band display, and the allocations as described by
[WWARA](https://www.wwara.org/wp-content/uploads/2021/12/WWARA-BAND-PLAN-20211218.pdf).

Starting with 2m:

![image](https://user-images.githubusercontent.com/82750/201172176-4173b503-9dff-4237-b0c4-0ecd6fe8e30c.png)

**Comment by mckoss** [comment]
See also the [IARU Region 2 Band Plan](https://www.iaru.org/wp-content/uploads/2020/01/R2-Band-Plan-2016.pdf)

**Comment by QCaudron** [comment]
Sounds like a fun little addition ! I could do this in matplotlib or something but I figure some cute interactive JS would be fun -- maybe where you can hover over a vertical band representing a frequency, and get a bubble showing the club and callsign or something. I'm probably asking for too much for a toy project...

I'm seeing this laid out quite simply -- maybe a thick, horizontal bar representing a band, with some vertical lines through it representing repeater outputs. We have several bands, so maybe we stack the band bars vertically. Just my first thought -- looking forward to seeing what you come up with !
