### ISSUE TITLE
Rounding in CSV file to nearest kHz is Wrong.

### ISSUE THREAD

**Issue by mckoss** [QCaudron/repeater_roundabout#27]
We have some stations with 500 Hz spacing:

![image](https://user-images.githubusercontent.com/82750/201234187-0b4dadc7-fb15-49d2-b9d9-1b50d2eedd22.png)

We are rounding the frequencies to 3 digits and losing this information (at least in the Icom csv file).

We do rounding to avoid numerical errors like continued mantissa xxx.xxx999999.

So - just round to 4 digits.

**Comment by QCaudron** [comment]
We are *amateurs* so, why not test in prod ? Throw something like this in there :

```python
assert df["Output (MHz)"].astype(str).str[-1].isin(["0", "5"]).all()
```

**Comment by QCaudron** [comment]
Fixed ! It's in main now.
