### ISSUE TITLE
Online / live logging

### ISSUE THREAD

**Issue by QCaudron** [QCaudron/repeater_roundabout#34]
Some suggested that being able to live-log on the website, in a set-and-forget fashion, could help increase logging rate. I think the idea is a page with basic localStorage for the user's callsign, and then a tabular entry widget where you could enter the callsign and channel you made a contact with / on, and have an (editable) auto timestamp. I think something as lightweight as possible would be best -- without a need to log in, for instance. This might be a sizeable feature to develop though.

Complication : can we have a list of stations spotted based on live logging in realtime ?

**Comment by paulpalinkas** [comment]
A thought: instead of all of that, a Discord channel where some of us would be available to help others with submitting their logs. I'd pitch in.

**Comment by QCaudron** [comment]
I hope that we are able to have a more lively Discord setup and, ideally, some more help going on, be it in logging or otherwise ! Thanks very much for the offer -- I'd love to have some folk help out in a more official ( or semi-official, if they prefer ) capacity !
