### ISSUE TITLE
Category winners

### ISSUE THREAD

**Issue by QCaudron** [QCaudron/repeater_roundabout#37]
Perhaps special shout-out to those who win special categories :

- Most repeater duplicates / most helpful on a repeater
- First log submitted
- Most repeaters activated
- ...

**Comment by paulpalinkas** [comment]
I thought Rich WB7J should get a shout out for his many contacts while traveling by public transit. 

I can't see it being made quantitative, but I thought it was a really cool thing to do in a way that logging miles by car wouldn't be.

**Comment by QCaudron** [comment]
I think that's a great idea.
