### ISSUE TITLE
Clean up auxiliary files for D878 CSV

### ISSUE THREAD

**Issue by mckoss** [QCaudron/repeater_roundabout#6]
Generate Scan List and Talk Group files programmatically rather than a static version now checked into the
assets folder.

**Comment by QCaudron** [comment]
#10 addresses half of this -- generating talk group files.

**Comment by QCaudron** [comment]
I think the two static files are now correct with CRLF line endings. Hoping they don't get stripped somewhere...

**Comment by mckoss** [comment]
#23 Fixes
