### ISSUE TITLE
Write more comprehensive documentation on using the CSV programming files.

### ISSUE THREAD

**Issue by mckoss** [QCaudron/repeater_roundabout#7]
Would be good to describe in more detail how to use CHIRP,  AnyTone, and ICOM programmer to install
the programming files into their respective radios.

Perhaps, even make a video for a representative radio model showing how to accomplish the programming for each type.

- UV5R - CHIRP
- TYT 9800 - CHIRP
- AT-D878 - D878
- ICOM 705 - Icom

**Comment by QCaudron** [comment]
I've taken a small stab at adding some Chirp instructions. We could go deeper, but it's beginning to look a lot like scope creep -- and there are some great resources out there already. I've linked to some of Dave Casler's videos, because Chirp's docs are a little tough to digest in places.

**Comment by mckoss** [comment]
Agreed.  I like your improvements.
