### ISSUE TITLE
Address 50-channel Scan List limit on D878

### ISSUE THREAD

**Issue by mckoss** [QCaudron/repeater_roundabout#9]
Not all the channels will fit in the scan list (max 50).  So, suggest to break them up into two groups

(perhaps 2m and 70cm groups)?

I don't think there's any way to scan all the frequencies in a Zone.

**Comment by QCaudron** [comment]
Hmmm, that's another annoying limitation. I wonder if we want to break out scan groups by geography rather than frequency ?

Alternatively, we can put scan lists on the backburner if it's a toughish problem.

**Comment by mckoss** [comment]
I like the geo-option maybe harder to automate (use GPS coords above and below a given latitude???).

Anyway - low prio.

**Comment by mckoss** [comment]
#23 implements the geo-option.
